<a href="https://colab.research.google.com/github/dannyryu4758/pythonStudy/blob/main/Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



- 관계 또는 레이블링 데이터로 쉽고 직관적으로 작업할 수 있도록 고안된 빠르고 유연하며 표현력이 뛰어난 데이터 구조를 제공하는 Python 패키지

## Pandas 객체
- 부동 소수점이 아닌 데이터 뿐만 아니라 부동 소수점 데이터에서도 결측 데이터(NaN으로 표시됨)를 쉽게 처리
- 크기 변이성(Size mutabillity) : DataFrame 및 고차원 객체에서 열을 삽입 및 삭제 기능
- 자동 및 명시적(explicit) 데이터 정렬 : 객체를 라벨 집합에 명시적으로 정렬하거나, 사용자가 라벨을 무시하고 Series, DataFrame 등의 계산에서 자동으로 데이터 조정 가능
- 데이터 세트에서 집계 및 변환을 위한 분할(split), 적용(apply), 결합(combine) 작업을 수행할 수 있는 강력하고 유연한 group_by 함수 제공
- 누락된 데이터 또는 다른 Python 및 Numpy 데이터 구조에서 서로 다른 인덱싱 데이터를 DataFrame 개체로 쉽게 변환
- 대용량 데이터 세트의 지능형 라벨 기반 슬라이싱, 고급 인덱싱 및 부분 집합 구하기 가능
- 직관적인 데이터 세트 병합 및 결합
- 데이터 세트의 유연한 재구성 및 피벗
- 축의 계층적 라벨링(눈금당 여러 개의 라벨을 가질 수 있음)
- 플랫파일(CSV 및 구분), Excel 파일, 데이터베이스 로딩 및 초고속 HDF5형식의 데이터 저장/로드에 사용되는 강력한 IO 도구
- 시계열 특정 기능 : 날짜 범위 생성 및 주파수 변환, 무빙 윈도우(moving window) 통계, 날짜 이동 및 지연

In [1]:
import numpy as np 
import pandas as pd
pd.__version__

'1.1.5'

### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75,1.0], index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [8]:
s['c']

0.5

In [9]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s

True

In [12]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
s[4]

0.25

In [14]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [15]:
# 중복되지 않는 값 출력
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# 각 값에 대한 갯수 확인
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [17]:
# 값이 있는 위치 확인
s.isin([0.25, 0,75])

2      True
4      True
6     False
8     False
10    False
dtype: bool

In [18]:
# 튜플을 시리즈로 변환하기
pop_tuple = {'서울특별시' : 9720846,
             '부산광역시' : 3404423,
             '인천광역시' : 2947217,
             '대구광역시' : 2427954,
             '대전광역시' : 1471040,
             '광주광역시' : 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [19]:
population['서울특별시']

9720846

In [20]:
# 슬리이싱
population['서울특별시' : '인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [22]:
# dictionary 를 DataFrame으로 변환 (누락값 자동 처리)
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [25]:
# 컬럼과 인덱스 설정하기
pd.DataFrame(np.random.rand(5,5), # 5 X 5 의 임의 숫자(0 ~ 1 사이 숫자)
             columns=['A','B','C','D','E'], 
             index=[1,2,3,4,5])

A         B         C         D         E
1  0.071718  0.048144  0.864074  0.922310  0.710097
2  0.001457  0.534330  0.023770  0.887288  0.877491
3  0.184721  0.810823  0.246972  0.617834  0.272164
4  0.206971  0.032642  0.661672  0.284367  0.144539
5  0.966476  0.617619  0.868629  0.385047  0.446869

In [26]:
# 남자 인구수 시리즈
male_tuple = {'서울특별시' : 4732275,
             '부산광역시' : 1668618,
             '인천광역시' : 1476813,
             '대구광역시' : 1198815,
             '대전광역시' : 734441,
             '광주광역시' : 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [27]:
# 여자 인구수 시리즈
female_tuple = {'서울특별시' : 4988571,
                '부산광역시' : 1735805,
                '인천광역시' : 1470404,
                '대구광역시' : 1229139,
                '대전광역시' : 736599,
                '광주광역시' : 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [80]:
# 시리즈들을 합쳐 데이터프레임 만들기
korea_df = pd.DataFrame({'인구수' : population,
                         '남자인구수':male,
                         '여자인구수':female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [30]:
# 사용 중인 인덱스 확인
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [31]:
# 컬럼 확인
korea_df.columns

Index(['인구수', '남자인수구', '여자인구수'], dtype='object')

In [32]:
# 컬럼명을 활용해 데이터 골라보기
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [34]:
korea_df['서울특별시':'인천광역시']

인구수    남자인수구    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


*   Index : 일반적인 index 객체이며, NumPy 배열 형식으로 축의 이름 표현
*   Int64Index : 정수 값을 위한 Index
*   MultiIndex : 단일 축에 여러 단계 색인을 표현하는 계층적 Index 객체 (튜플의 배열과 유사)
*   DatetimeIndex : NumPy의 datetime64 타입으로 타임스탬프 저장
*   PeriodIndex : 기간 데이터를 위한 Index




In [35]:
# 인덱스 만들기
idx = pd.Index([2,4,5,6,10])
idx

Int64Index([2, 4, 5, 6, 10], dtype='int64')

In [36]:
# 인덱스 선택 조회
idx[1]

4

In [37]:
# 슬리이싱
idx[1:2:2]

Int64Index([4], dtype='int64')

In [38]:
idx[-1]

10

In [40]:
# step 2 ==> 두칸씩
idx[::2]

Int64Index([2, 5, 10], dtype='int64')

In [41]:
print(idx)
print(idx.size)
print(idx.shape) # 다중배열 형태
print(idx.ndim)  # 차원
print(idx.dtype) # 데이터 타입

Int64Index([2, 4, 5, 6, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산
| 연산자 | 메소드 | 설명 |
|--------|--------|------|
|  | `append` | 색인 객체를 추가한 새로운 색인 반환 |
|  | `difference` | 색인의 차집합 반환 |
| `&`  | `intersection` | 색인의 교집합 반환 |
| `\|` | `union` | 색인의 합집합 반환 |
|  | `isin` | 색인이 존재하는지 여부를 boolean 배열로 반환 |
|  | `delete` | 색인이 삭제된 새로운 색인 반환 |
|  | `drop` | 값이 삭제된 새로운 색인 반환 |
|  | `insert` | 색인이 추가된 새로운 색인 반환 |
|  | `is_monotonic` | 색인이 단조성을 가지면 True |
|  | `is_unique` | 중복되는 색인이 없다면 True |
|  | `unique` | 색인에서 중복되는 요소를 제거하고 유일한 값만 반환 |

In [51]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
# append : 색인객체 추가
print(idx1.append(idx2))
# difference : idx1 에만 있는 값
print(idx1.difference(idx2))
print(idx1 - idx2)
# intersection : 중복 값 확인
print(idx1.intersection(idx2))
print(idx1 & idx2)
# union 중복값 제거한 합집합
print(idx1.union(idx2))
print(idx1 | idx2)
# 하나의 값 삭제하기
print(idx1.delete(0))
print(idx1.drop(1))
# 여집합
print(idx1 ^ idx2) 

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [52]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
            index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [53]:
s['b']

0.25

In [54]:
'b' in s

True

In [56]:
# 키(index) 출력하기
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [59]:
# 각 값 출력하기
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [60]:
# 새로운 인덱싱 추가
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [61]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [62]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [63]:
# 조건 필터링
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [64]:
s[['a','b','c']]

a    0.00
b    0.25
c    0.50
dtype: float64

### Series 인덱싱

In [65]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'], 
              index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [66]:
# 지정해준 index 값을 통한 조회
s[1]

'a'

In [67]:
s[2:4]

5    c
7    d
dtype: object

In [68]:
# 기본 index 0, 1, 2, ... 를 활용한 조회
s.iloc[1]

'b'

In [70]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [71]:
# 새로운 인덱스 구축하기
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [72]:
# 새로운 인덱스 구축 + 비어있는 값은 그 앞의 값과 동일하게 넣기
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱
| 메소드 | 설명 |
|--------|------|
| `df[val]` | 하나의 컬럼 또는 여러 컬럼을 선택 |
| `df.loc[val]` | 라벨값으로 로우의 부분집합 선택 |
| `df.loc[:, val]` | 라벨값으로 컬럼의 부분집합 선택 |
| `df.loc[val1, val2]` | 라벨값으로 로우와 컬럼의 부분집합 선택 |
| `df.iloc[:, where]` | 정수 색인으로 컬럼의 부분집합 선택 |
| `df.iloc[where_i, where_j]` | 정수 색인으로 로우와 컬럼의 부분집한 선택 |
| `df.at[label_i, label_j]` | 로우와 컬럼의 라벨로 단일 값 선택 |
| `df.iat[i, j]` | 로우와 컬럼의 정수 색인으로 단일 값 선택 |
| `reindex` | 하나 이상의 축을 새로운 색인으로 재색인 |
| `get_value, set_value` | 로우와 컬럼의 이름으로 값 선택 |

In [77]:
korea_df

인구수    남자인수구    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [81]:
# 컬럼에 해당하는 값만 선택하기
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [82]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [83]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [84]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [85]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [86]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [87]:
# 피벗하기
korea_df.T

서울특별시         부산광역시  ...         대전광역시         광주광역시
인구수    9.720846e+06  3.404423e+06  ...  1.471040e+06  1.455048e+06
남자인구수  4.732275e+06  1.668618e+06  ...  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  ...  7.365990e+05  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  ...  9.970703e+01  9.796895e+01

[4 rows x 6 columns]

In [89]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [90]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [93]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [95]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [97]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [99]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [100]:
korea_df.loc[(korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [101]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [103]:
korea_df.iloc[:3,:2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

#### 다중 인덱스 생성

#### 인덱싱 및 슬라이싱

#### 다중 인덱스 재정렬

## 데이터 연산

### 연산자 범용 함수


#### add()

#### sub() / subtract()

#### mul() / multply()




#### truediv() /  div() / divide() / floordiv()

#### mod()

#### pow()

### 정렬(Sort)

### 순위(Ranking)


### 고성능 연산

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly